name: chatapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies
  firebase_core: ^3.8.0 # Firebase core to initialize Firebase
  firebase_auth: ^5.3.3  # Firebase Authentication for user login/signup
  cloud_firestore: ^5.5.0  # Cloud Firestore for storing user data and messages

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/games.jpg
    - assets/business.jpg
    - assets/health.jpg
    - assets/study.jpg
