// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUkx2RmQYkTYgHPj-3hcbtUZKdF7yt3N4',
    appId: '1:1062494770957:web:4a206aaa315eb1b22dc244',
    messagingSenderId: '1062494770957',
    projectId: 'chat-890e9',
    authDomain: 'chat-890e9.firebaseapp.com',
    storageBucket: 'chat-890e9.firebasestorage.app',
    measurementId: 'G-REX1WMR1WL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX2X6Gq55oKuqtWNNh2bEN1QrpbMZgo44',
    appId: '1:1062494770957:android:502af71c0bcc9b552dc244',
    messagingSenderId: '1062494770957',
    projectId: 'chat-890e9',
    storageBucket: 'chat-890e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2axZYyl8u7AakASAoZQfKKAt_fqW9fyU',
    appId: '1:1062494770957:ios:6ad86e5c3af7774f2dc244',
    messagingSenderId: '1062494770957',
    projectId: 'chat-890e9',
    storageBucket: 'chat-890e9.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2axZYyl8u7AakASAoZQfKKAt_fqW9fyU',
    appId: '1:1062494770957:ios:6ad86e5c3af7774f2dc244',
    messagingSenderId: '1062494770957',
    projectId: 'chat-890e9',
    storageBucket: 'chat-890e9.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUkx2RmQYkTYgHPj-3hcbtUZKdF7yt3N4',
    appId: '1:1062494770957:web:bbab903e530218982dc244',
    messagingSenderId: '1062494770957',
    projectId: 'chat-890e9',
    authDomain: 'chat-890e9.firebaseapp.com',
    storageBucket: 'chat-890e9.firebasestorage.app',
    measurementId: 'G-ZG9TKMWGTN',
  );
}
